version: '3.4'

services:
    mongo:
        image: mongo:5.0.14
        container_name: mongo
        restart: always
        expose:
            - 27017
        volumes:
            - ./mongodata:/data/db
        env_file:
            - ./secret/.env
        command: --quiet --logpath /var/log/mongodb/mongod-config.log
    web:
        build: ./web
        restart: always
        depends_on:
            - mongo
        ports:
            - 80:8080
        volumes:
            - ./web:/usr/src/app
            - ./public:/usr/src/app/public
            - /usr/src/app/node_modules
        env_file:
            - ./secret/.env
        command: npm run start:dev
    mongoexpress:
        container_name: mongo-express
        image: mongo-express:0.49.0
        ports:
            - "8081:8081"
        env_file:
            - ./secret/.env
        depends_on:
            - mongo
        restart: always
